#!/bin/bash

# Updates
echo "Update started at:" > /home/john/.update.log
date >> /home/john/.update.log
echo "Checking for and installing updates..."
sudo pacman -Syyu >> /home/john/.update.log >> /home/john/.update.log
echo "Checking for orpaned packages..."
sudo pacman -Qdt >> /home/john/.update.log >> /home/john/.update.log
echo "Clearing package cache..."
sudo pacman -Sc >> /home/john/.update.log >> /home/john/.update.log
echo "Complete!" | tee -a /home/john/.update.log

echo "Updating AUR packages" sudo pacaur -Syyu >> /home/john/.aurupdate.log >> /home/john/.aurupdate.logpacaur 
